### ISSUE TITLE
create a yaml config file for creating artbox projects

### ISSUE THREAD

**Issue by xmnlab** [ggpedia/artbox#14]
```yaml

version: 0.1  # spec version
name: OSL Happy New Year  # project name

scenes:
  - start: 0  # milliseconds
    end: 1000  # milliseconds
    text: 
      content: Happy New Year 2024
      effects:
        - type: shadow  # possible options: outline, shadow, reflection, glow, bevels
          size: 0.3  # px
          color: "#fafafa"
    voice:
      from-text: true  # default false
      speed: 1.0  # 1.0 is the normal speed
      lang: en
      engine: edge-ts  # default: edge-ts, options: edge-ts, gts
      kind: ...  # TBD
    background:
      layers:
        - kind: youtube  # current options are: youtube, file, url
          source: https://www.youtube.com/watch?v=4i8hbDnM52Q
          repeat: true  # default true
          keep-audio: false  # default false
       - kind: file
         source: ./images/logo.png
         size: 100  # px
         x: 100  # px
         y: 100  # px
```
